# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyterate Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install Pyterate
      run: python setup.py install
    - name: Debug scripts
      run: |
        python continuous-integration/platform.py
    - name: Make API doc
      run: pyterate-rst-api Pyterate
    - name: Run examples
      run: pyterate --only-run
    # - name: Make examples RST
    #   run: |
    #     # --skip-rst --skip-external-figure --skip-notebook
    #     pyterate --skip-external-figure --skip-notebook
